stages:
  - build_job
  - syft_job
  - grype_sbom_job
  - trivy_job

build_job:
  stage: build_job
  script:
    - docker build -t dvwa .
  only:
    - main

syft_job:
  stage: syft_job
  script:
    - syft docker:dvwa -o json=sbom.json -o text=syft_report.txt
  artifacts:
    untracked: true
    paths:
      - syft_report.txt
  only:
    - main

grype_sbom_job:
  stage: grype_sbom_job
  script:
    - grype sbom:./sbom.json -o table > grype_report.txt
  dependencies: 
    - syft_job
  artifacts:
    paths:
      - grype_report.txt
  only:
    - main

trivy_job:
  stage: trivy_job
  script:
   - trivy image dvwa -o trivy_report_1.html
   - trivy image dvwa --ignore-unfixed --severity HIGH,CRITICAL -o trivy_report_2.html
   - trivy image dvwa --ignore-unfixed --severity CRITICAL --exit-code 1 -o trivy_report_3.html
  artifacts:
    paths:
      - trivy_report_1.html
      - trivy_report_2.html
      - trivy_report_3.html
  only:
   - main
