name: project
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.0.9
  http: ^0.13.5
  internet_connection_checker: ^1.0.0+1
  json_annotation: ^4.6.0
  path_provider: ^2.0.11
  share_plus: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.1
  json_serializable: ^6.0.0
  flutter_launcher_icons: "^0.10.0"

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/icon.png"
  min_sdk_android: 16

flutter:
  uses-material-design: true
