stages:
  - build
  - linter
  - sonar_cloud

build:
  stage: build
  image: maven
  script:
    - chmod +x mvnw
    - ./mvnw package
  artifacts:
    paths:
      - target/main-0.0.1-SNAPSHOT.jar

linter:
  stage: linter
  image: maven
  script:
    - chmod +x mvnw
    - ./mvnw spotbugs:spotbugs
  dependencies:
    - build

sonar_cloud:
  stage: sonar_cloud
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  image: maven
  allow_failure: true
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - >
      ./mvnw package sonar:sonar \
        -Dsonar.projectKey=project-43972561-bot-8b5249065b413969_lab2-nouralla \
        -Dsonar.projectName=project-43972561-bot-8b5249065b413969_lab2-nouralla \
        -Dsonar.host.url=https://sonarcloud.io \
        -Dsonar.login=${SONAR_TOKEN} \
        -Dsonar.sources=./src/main/java/
  only:
    - master
