stages:
  - build
  - deploy

build:
  stage: build
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin
  script:
    - docker build -t "$CI_REGISTRY_IMAGE" app
    - docker push "$CI_REGISTRY_IMAGE" --all-tags
  rules:
    - if: $CI_COMMIT_BRANCH	 == "main"
    - changes: [app]

deploy:
  stage: deploy
  script:
    - kubectl apply -f k8s/deployment.yaml -n app
  rules:
    - if: $CI_COMMIT_BRANCH	 == "main"
    - changes: [app]
