apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  secret-key: c2VjcmV0LXZhbHVlCg==
---

# Deployment using the secret

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: sh3b0/app
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        env:
          - name: APP_SECRET
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: secret-key
        ports:
        - containerPort: 8080
