apiVersion: v1
kind: Namespace
metadata:
  name: ns-1

---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-2

---
apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  namespace: ns-1
spec:
  containers:
  - name: app
    image: sh3b0/app
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080

---
apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  namespace: ns-2
spec:
  containers:
  - name: app
    image: sh3b0/app
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
