name: Release and Scan

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - ".github/workflows/**"
  pull_request:
    types:
      - opened
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          username: sh3b0
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v3
        with:
          push: true
          tags: sh3b0/nearbirds:latest
          cache-from: type=registry,ref=sh3b0/nearbirds:latest
          cache-to: type=inline
  
  scan:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - uses: actions/checkout@v3
      - name: Run npm audit to check project for vulnerabilities
        run: npm audit
