stages:
  - build_and_run
  - hawk_scan
  - zap_scan
  - deploy_to_k8s

build_and_run:
  stage: build_and_run
  script:
    - docker build -t milkshakers/juice-shop juice-shop
    - docker start juice-shop || docker run -d --name juice-shop -p3000:3000 --network gitlab_default milkshakers/juice-shop

hawk_scan:
  stage: hawk_scan
  script:
    - /hawk-2.9.0/hawk --no-color --api-key=${HAWK_API_KEY} scan

zap_scan:
  stage: zap_scan
  script:
    - |
      docker run --rm --network gitlab_default -v /tmp:/zap/wrk -t \
      owasp/zap2docker-weekly zap-baseline.py -t http://juice-shop:3000 -I -s \
      -r zap_baseline_report.html
    - |
      docker run --rm --network gitlab_default -v /tmp:/zap/wrk -t \
      owasp/zap2docker-weekly zap-full-scan.py -t http://juice-shop:3000 -I -s \
      -r zap_fullscan_report.html -n /zap/wrk/authenticated.context
    - |
      docker run --rm --network gitlab_default -v /tmp:/zap/wrk -t \
      owasp/zap2docker-weekly zap-api-scan.py -t http://juice-shop:3000/b2b/v2 -I -s \
      -f openapi -r zap_api_report.html

deploy_to_k8s:
  stage: deploy_to_k8s
  script:
    - helm upgrade --install juice-shop chart --cleanup-on-fail --wait
